# Application (en Docker)
spring.application.name=api-gateway
server.port=8080

# OAuth2 Resource Server - Keycloak (Docker internal network)
# Solo jwk-set-uri, así el gateway baja las claves desde Keycloak dentro de la red docker
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/tpi-backend/protocol/openid-connect/certs

# Microservices URLs (Docker internal network)
clientes.service.url=http://clientes-ms:8081
ubicaciones.service.url=http://ubicaciones-ms:8084
solicitudes.service.url=http://solicitudes-ms:8082
transporte.service.url=http://transporte-ms:8083

# Logging para producción / docker (menos ruido)
logging.level.org.springframework.security=INFO
logging.level.org.springframework.security.oauth2=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.cloud.gateway=INFO
