spring:
  application:
    name: Ubicaciones-Microservicio
  datasource:
    url: jdbc:mysql://localhost:3306/dbubicaciones
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bda-realm  # Puerto de Keycloak

server:
  port: 8082  # Puerto del microservicio (diferente a Keycloak)

springdoc:
  swagger-ui:
    path: /swagger-ui.html

google:
  maps:
    apikey: AIzaSyCKI8-srVChwYKMKiZbuHMXVcAntVceUZQ

microservicio:
  contenedores:
    url: http://localhost:8081/api/contenedores