spring.application.name=clientes-ms
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.nxlqnoahtsmvujhuzkwi
spring.datasource.password=grupo16
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update