spring.application.name=transporte
server.port=8084
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.nxlqnoahtsmvujhuzkwi
spring.datasource.password=grupo16
spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=300000
