spring.application.name=Solicitudes
server.port=8083
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.nxlqnoahtsmvujhuzkwi
spring.datasource.password=grupo16
spring.jpa.hibernate.ddl-auto=update